@node    mumo'o, xamo'o, vomo'o, Top
@chapter mumo'o se djusku le ciftoldi


@c                                CHAPTER V

@c                        Advice from a Caterpillar


@c      The Caterpillar and Alice looked at each other for some time in
@c    silence:  at last the Caterpillar took the hookah out of its
@c    mouth, and addressed her in a languid, sleepy voice.

@c      `Who are YOU?' said the Caterpillar.

@c      This was not an encouraging opening for a conversation.  Alice
@c    replied, rather shyly, `I--I hardly know, sir, just at present--
@c    at least I know who I WAS when I got up this morning, but I think
@c    I must have been changed several times since then.'

@c      `What do you mean by that?' said the Caterpillar sternly.
@c    `Explain yourself!'

@c      `I can't explain MYSELF, I'm afraid, sir' said Alice, `because
@c    I'm not myself, you see.'

@c      `I don't see,' said the Caterpillar.

@c      `I'm afraid I can't put it more clearly,' Alice replied very
@c    politely, `for I can't understand it myself to begin with; and
@c    being so many different sizes in a day is very confusing.'

@c      `It isn't,' said the Caterpillar.

@c      `Well, perhaps you haven't found it so yet,' said Alice; `but
@c    when you have to turn into a chrysalis--you will some day, you
@c    know--and then after that into a butterfly, I should think you'll
@c    feel it a little queer, won't you?'

@c      `Not a bit,' said the Caterpillar.

@c      `Well, perhaps your feelings may be different,' said Alice;
@c    `all I know is, it would feel very queer to ME.'

@c      `You!' said the Caterpillar contemptuously.  `Who are YOU?'

@c      Which brought them back again to the beginning of the
@c    conversation.  Alice felt a little irritated at the Caterpillar's
@c    making such VERY short remarks, and she drew herself up and said,
@c    very gravely, `I think, you ought to tell me who YOU are, first.'

@c      `Why?' said the Caterpillar.

@c      Here was another puzzling question; and as Alice could not
@c    think of any good reason, and as the Caterpillar seemed to be in
@c    a VERY unpleasant state of mind, she turned away.

@c      `Come back!' the Caterpillar called after her.  `I've something
@c    important to say!'

@c      This sounded promising, certainly:  Alice turned and came back
@c    again.

@c      `Keep your temper,' said the Caterpillar.

@c      `Is that all?' said Alice, swallowing down her anger as well as
@c    she could.

@c      `No,' said the Caterpillar.

@c      Alice thought she might as well wait, as she had nothing else
@c    to do, and perhaps after all it might tell her something worth
@c    hearing.  For some minutes it puffed away without speaking, but
@c    at last it unfolded its arms, took the hookah out of its mouth
@c    again, and said, `So you think you're changed, do you?'

@c      `I'm afraid I am, sir,' said Alice; `I can't remember things as
@c    I used--and I don't keep the same size for ten minutes together!'

@c      `Can't remember WHAT things?' said the Caterpillar.

@c      `Well, I've tried to say "HOW DOTH THE LITTLE BUSY BEE," but it
@c    all came different!' Alice replied in a very melancholy voice.

@c      `Repeat, "YOU ARE OLD, FATHER WILLIAM,"' said the Caterpillar.

@c      Alice folded her hands, and began:--

@c        `You are old, Father William,' the young man said,
@c          `And your hair has become very white;
@c        And yet you incessantly stand on your head--
@c          Do you think, at your age, it is right?'

@c        `In my youth,' Father William replied to his son,
@c          `I feared it might injure the brain;
@c        But, now that I'm perfectly sure I have none,
@c          Why, I do it again and again.'

@c        `You are old,' said the youth, `as I mentioned before,
@c          And have grown most uncommonly fat;
@c        Yet you turned a back-somersault in at the door--
@c          Pray, what is the reason of that?'

@c        `In my youth,' said the sage, as he shook his grey locks,
@c          `I kept all my limbs very supple
@c        By the use of this ointment--one shilling the box--
@c          Allow me to sell you a couple?'

@c        `You are old,' said the youth, `and your jaws are too weak
@c          For anything tougher than suet;
@c        Yet you finished the goose, with the bones and the beak--
@c          Pray how did you manage to do it?'

@c        `In my youth,' said his father, `I took to the law,
@c          And argued each case with my wife;
@c        And the muscular strength, which it gave to my jaw,
@c          Has lasted the rest of my life.'

@c        `You are old,' said the youth, `one would hardly suppose
@c          That your eye was as steady as ever;
@c        Yet you balanced an eel on the end of your nose--
@c          What made you so awfully clever?'

@c        `I have answered three questions, and that is enough,'
@c          Said his father; `don't give yourself airs!
@c        Do you think I can listen all day to such stuff?
@c          Be off, or I'll kick you down stairs!'


@c      `That is not said right,' said the Caterpillar.

@c      `Not QUITE right, I'm afraid,' said Alice, timidly; `some of the
@c    words have got altered.'

@c      `It is wrong from beginning to end,' said the Caterpillar
@c    decidedly, and there was silence for some minutes.

@c      The Caterpillar was the first to speak.

@c      `What size do you want to be?' it asked.

@c      `Oh, I'm not particular as to size,' Alice hastily replied;
@c    `only one doesn't like changing so often, you know.'

@c      `I DON'T know,' said the Caterpillar.

@c      Alice said nothing:  she had never been so much contradicted in
@c    her life before, and she felt that she was losing her temper.

@c      `Are you content now?' said the Caterpillar.

@c      `Well, I should like to be a LITTLE larger, sir, if you
@c    wouldn't mind,' said Alice:  `three inches is such a wretched
@c    height to be.'

@c      `It is a very good height indeed!' said the Caterpillar
@c    angrily, rearing itself upright as it spoke (it was exactly three
@c    inches high).

@c      `But I'm not used to it!' pleaded poor Alice in a piteous tone.
@c    And she thought of herself, `I wish the creatures wouldn't be so
@c    easily offended!'

@c      `You'll get used to it in time,' said the Caterpillar; and it
@c    put the hookah into its mouth and began smoking again.

@c      This time Alice waited patiently until it chose to speak again.
@c    In a minute or two the Caterpillar took the hookah out of its
@c    mouth and yawned once or twice, and shook itself.  Then it got
@c    down off the mushroom, and crawled away in the grass, merely
@c    remarking as it went, `One side will make you grow taller, and
@c    the other side will make you grow shorter.'

@c      `One side of WHAT?  The other side of WHAT?' thought Alice to
@c    herself.

@c      `Of the mushroom,' said the Caterpillar, just as if she had
@c    asked it aloud; and in another moment it was out of sight.

@c      Alice remained looking thoughtfully at the mushroom for a
@c    minute, trying to make out which were the two sides of it; and as
@c    it was perfectly round, she found this a very difficult question.
@c    However, at last she stretched her arms round it as far as they
@c    would go, and broke off a bit of the edge with each hand.

@c      `And now which is which?' she said to herself, and nibbled a
@c    little of the right-hand bit to try the effect:  the next moment
@c    she felt a violent blow underneath her chin:  it had struck her
@c    foot!

@c      She was a good deal frightened by this very sudden change, but
@c    she felt that there was no time to be lost, as she was shrinking
@c    rapidly; so she set to work at once to eat some of the other bit.
@c    Her chin was pressed so closely against her foot, that there was
@c    hardly room to open her mouth; but she did it at last, and
@c    managed to swallow a morsel of the lefthand bit.


@c         *       *       *       *       *       *       *

@c             *       *       *       *       *       *

@c         *       *       *       *       *       *       *

@c      `Come, my head's free at last!' said Alice in a tone of
@c    delight, which changed into alarm in another moment, when she
@c    found that her shoulders were nowhere to be found:  all she could
@c    see, when she looked down, was an immense length of neck, which
@c    seemed to rise like a stalk out of a sea of green leaves that lay
@c    far below her.

@c      `What CAN all that green stuff be?' said Alice.  `And where
@c    HAVE my shoulders got to?  And oh, my poor hands, how is it I
@c    can't see you?'  She was moving them about as she spoke, but no
@c    result seemed to follow, except a little shaking among the
@c    distant green leaves.

@c      As there seemed to be no chance of getting her hands up to her
@c    head, she tried to get her head down to them, and was delighted
@c    to find that her neck would bend about easily in any direction,
@c    like a serpent.  She had just succeeded in curving it down into a
@c    graceful zigzag, and was going to dive in among the leaves, which
@c    she found to be nothing but the tops of the trees under which she
@c    had been wandering, when a sharp hiss made her draw back in a
@c    hurry:  a large pigeon had flown into her face, and was beating
@c    her violently with its wings.

@c      `Serpent!' screamed the Pigeon.

@c      `I'm NOT a serpent!' said Alice indignantly.  `Let me alone!'

@c      `Serpent, I say again!' repeated the Pigeon, but in a more
@c    subdued tone, and added with a kind of sob, `I've tried every
@c    way, and nothing seems to suit them!'

@c      `I haven't the least idea what you're talking about,' said
@c    Alice.

@c      `I've tried the roots of trees, and I've tried banks, and I've
@c    tried hedges,' the Pigeon went on, without attending to her; `but
@c    those serpents!  There's no pleasing them!'

@c      Alice was more and more puzzled, but she thought there was no
@c    use in saying anything more till the Pigeon had finished.

@c      `As if it wasn't trouble enough hatching the eggs,' said the
@c    Pigeon; `but I must be on the look-out for serpents night and
@c    day!  Why, I haven't had a wink of sleep these three weeks!'

@c      `I'm very sorry you've been annoyed,' said Alice, who was
@c    beginning to see its meaning.

@c      `And just as I'd taken the highest tree in the wood,' continued
@c    the Pigeon, raising its voice to a shriek, `and just as I was
@c    thinking I should be free of them at last, they must needs come
@c    wriggling down from the sky!  Ugh, Serpent!'

@c      `But I'm NOT a serpent, I tell you!' said Alice.  `I'm a--I'm
@c    a--'

@c      `Well!  WHAT are you?' said the Pigeon.  `I can see you're
@c    trying to invent something!'

@c      `I--I'm a little girl,' said Alice, rather doubtfully, as she
@c    remembered the number of changes she had gone through that day.

@c      `A likely story indeed!' said the Pigeon in a tone of the
@c    deepest contempt.  `I've seen a good many little girls in my
@c    time, but never ONE with such a neck as that!  No, no!  You're a
@c    serpent; and there's no use denying it.  I suppose you'll be
@c    telling me next that you never tasted an egg!'

@c      `I HAVE tasted eggs, certainly,' said Alice, who was a very
@c    truthful child; `but little girls eat eggs quite as much as
@c    serpents do, you know.'

@c      `I don't believe it,' said the Pigeon; `but if they do, why
@c    then they're a kind of serpent, that's all I can say.'

@c      This was such a new idea to Alice, that she was quite silent
@c    for a minute or two, which gave the Pigeon the opportunity of
@c    adding, `You're looking for eggs, I know THAT well enough; and
@c    what does it matter to me whether you're a little girl or a
@c    serpent?'

@c      `It matters a good deal to ME,' said Alice hastily; `but I'm
@c    not looking for eggs, as it happens; and if I was, I shouldn't
@c    want YOURS:  I don't like them raw.'

@c      `Well, be off, then!' said the Pigeon in a sulky tone, as it
@c    settled down again into its nest.  Alice crouched down among the
@c    trees as well as she could, for her neck kept getting entangled
@c    among the branches, and every now and then she had to stop and
@c    untwist it.  After a while she remembered that she still held the
@c    pieces of mushroom in her hands, and she set to work very
@c    carefully, nibbling first at one and then at the other, and
@c    growing sometimes taller and sometimes shorter, until she had
@c    succeeded in bringing herself down to her usual height.

@c      It was so long since she had been anything near the right size,
@c    that it felt quite strange at first; but she got used to it in a
@c    few minutes, and began talking to herself, as usual.  `Come,
@c    there's half my plan done now!  How puzzling all these changes
@c    are!  I'm never sure what I'm going to be, from one minute to
@c    another!  However, I've got back to my right size:  the next
@c    thing is, to get into that beautiful garden--how IS that to be
@c    done, I wonder?'  As she said this, she came suddenly upon an
@c    open place, with a little house in it about four feet high.
@c    `Whoever lives there,' thought Alice, `it'll never do to come
@c    upon them THIS size:  why, I should frighten them out of their
@c    wits!'  So she began nibbling at the righthand bit again, and did
@c    not venture to go near the house till she had brought herself
@c    down to nine inches high.
