@node    mumo'o, xamo'o, vomo'o, Top
@chapter mumo'o se djusku le ciftoldi


@c                                CHAPTER V

@c                        Advice from a Caterpillar


@c      The Caterpillar and Alice looked at each other for some time in
@c    silence:  at last the Caterpillar took the hookah out of its
@c    mouth, and addressed her in a languid, sleepy voice.

le ciftoldi ku ce la alis. ze'a simxu le za'i smaji catlu le
drata cmima .i bazubo le ciftoldi mo'ize'o bevri le nargile fo le
moklu gi'e .o'udai .a'inaidai cusku fi ko'a
@c stidi zo jaurdamtci seba'i lu marna tubnu li'u
@c Found the right word: nargile.
@c "le drata cmima" seems superfluous as it is implied by "simxu" -phma

@c      `Who are YOU?' said the Caterpillar.

.i lu doi ba'e ma li'u se cusku le ciftoldi
@c The English rhymes, so some variation on "do mo" is probably
@c a good idea. --Adam


@c      This was not an encouraging opening for a conversation.  Alice
@c    replied, rather shyly, `I--I hardly know, sir, just at present--
@c    at least I know who I WAS when I got up this morning, but I think
@c    I must have been changed several times since then.'

.i di'u na'e xamgu mukti le nu co'a casnu .i la alis. .u'onaisai cusku
lu mi .y. si mi na'e mulno djuno ga'inai ca le cabna .isa'unai mi djuno
mi'e makau ca le nu mi puza ckana cliva le cabycerni .iku'i pe'i mi
so'oroi je puza ze'aca binxo

@c      `What do you mean by that?' said the Caterpillar sternly.
@c    `Explain yourself!'

.i lu ma smuni di'u li'u se cusku .o'onairu'edai ga'idai le ciftoldi fa lu
ko ko ciksi li'u

@c      `I can't explain MYSELF, I'm afraid, sir' said Alice, `because
@c    I'm not myself, you see.'

.i lu mi na kakne le nu ciksi mi .i .u'u ga'inai li'u se cusku la alis.
fa lu .iki'ubo le ka mi na du mi ku do se ganse li'u

@c      `I don't see,' said the Caterpillar.

.i lu mi na ganse li'u se cusku le ciftoldi

@c      `I'm afraid I can't put it more clearly,' Alice replied very
@c    politely, `for I can't understand it myself to begin with; and
@c    being so many different sizes in a day is very confusing.'

.i lu .u'u mi na kakne le nu xagmau cusku de'u li'u la alis. traji clite
se cusku  fa lu ki'u mi zu'u na jimpe la'e de'u .ije le nu du'eroi galfi
le ni mi clani cu traji cfipu li'u

@c      `It isn't,' said the Caterpillar.

.i lu na drani li'u le ciftoldi cu se cusku

@c      `Well, perhaps you haven't found it so yet,' said Alice; `but
@c    when you have to turn into a chrysalis--you will some day, you
@c    know--and then after that into a butterfly, I should think you'll
@c    feel it a little queer, won't you?'

.i lu .o'ocu'i pe'i do puze'e ca na tugni li'u se cusku la alis. fa lu
.iku'i ca le nu do binxo le todbi'olanka to le du'u do baca'a binxo
teti'u da ku se djuno .a'o do toi gi'ebabo binxo le toldi .i pe'i do
cinmo le milxe se cizra .i xu do tugni li'u

@c      `Not a bit,' said the Caterpillar.

.i lu na go'i li'u se cusku le ciftoldi

@c      `Well, perhaps your feelings may be different,' said Alice;
@c    `all I know is, it would feel very queer to ME.'

lu .o'ocu'i pe'i do cnimo le drata sei la alis. cusku .i mi djuno
ledu'u ba'e mi da'i cinmo le se cizra li'u

@c      `You!' said the Caterpillar contemptuously.  `Who are YOU?'
.i lu ba'e do ga'i sei le ciftoldi cu tolsi'a cusku .i do ba'e ma li'u

@c      Which brought them back again to the beginning of the
@c    conversation.  Alice felt a little irritated at the Caterpillar's
@c    making such VERY short remarks, and she drew herself up and said,
@c    very gravely, `I think, you ought to tell me who YOU are, first.'
.i di'u xruti ra le krasi be le pu'u simtavla .i la .alis cu milxe fanza
le nu le ciftoldi cu cusku le tcetordi pinka gi'e sanli zenba gi'e tcejunri
cusku lu pe'i do .ei cusku le sedu'u ba'e do mo puku li'u


@c      `Why?' said the Caterpillar.
.i lu ki'u ma li'u se cusku le ciftoldi

@c      Here was another puzzling question; and as Alice could not
@c    think of any good reason, and as the Caterpillar seemed to be in
@c    a VERY unpleasant state of mind, she turned away.

@c      `Come back!' the Caterpillar called after her.  `I've something
@c    important to say!'
.i lu ko xruti ko sei le ciftoldi fa'a krixa .i mi le vajni .ei cu cusku li'u

@c      This sounded promising, certainly:  Alice turned and came back
@c    again.

@c      `Keep your temper,' said the Caterpillar.

@c      `Is that all?' said Alice, swallowing down her anger as well as
@c    she could.

@c      `No,' said the Caterpillar.

@c      Alice thought she might as well wait, as she had nothing else
@c    to do, and perhaps after all it might tell her something worth
@c    hearing.  For some minutes it puffed away without speaking, but
@c    at last it unfolded its arms, took the hookah out of its mouth
@c    again, and said, `So you think you're changed, do you?'

@c      `I'm afraid I am, sir,' said Alice; `I can't remember things as
@c    I used--and I don't keep the same size for ten minutes together!'

@c      `Can't remember WHAT things?' said the Caterpillar.

@c      `Well, I've tried to say "HOW DOTH THE LITTLE BUSY BEE," but it
@c    all came different!' Alice replied in a very melancholy voice.

@c      `Repeat, "YOU ARE OLD, FATHER WILLIAM,"' said the Caterpillar.

@c      Alice folded her hands, and began:--

@c        `You are old, Father William,' the young man said,
@c          `And your hair has become very white;
@c        And yet you incessantly stand on your head--
@c          Do you think, at your age, it is right?'

@c        `In my youth,' Father William replied to his son,
@c          `I feared it might injure the brain;
@c        But, now that I'm perfectly sure I have none,
@c          Why, I do it again and again.'

@c        `You are old,' said the youth, `as I mentioned before,
@c          And have grown most uncommonly fat;
@c        Yet you turned a back-somersault in at the door--
@c          Pray, what is the reason of that?'

@c        `In my youth,' said the sage, as he shook his grey locks,
@c          `I kept all my limbs very supple
@c        By the use of this ointment--one shilling the box--
@c          Allow me to sell you a couple?'

@c        `You are old,' said the youth, `and your jaws are too weak
@c          For anything tougher than suet;
@c        Yet you finished the goose, with the bones and the beak--
@c          Pray how did you manage to do it?'

@c        `In my youth,' said his father, `I took to the law,
@c          And argued each case with my wife;
@c        And the muscular strength, which it gave to my jaw,
@c          Has lasted the rest of my life.'

@c        `You are old,' said the youth, `one would hardly suppose
@c          That your eye was as steady as ever;
@c        Yet you balanced an eel on the end of your nose--
@c          What made you so awfully clever?'

@c        `I have answered three questions, and that is enough,'
@c          Said his father; `don't give yourself airs!
@c        Do you think I can listen all day to such stuff?
@c          Be off, or I'll kick you down stairs!'


@c      `That is not said right,' said the Caterpillar.

@c      `Not QUITE right, I'm afraid,' said Alice, timidly; `some of the
@c    words have got altered.'

@c      `It is wrong from beginning to end,' said the Caterpillar
@c    decidedly, and there was silence for some minutes.

@c      The Caterpillar was the first to speak.

@c      `What size do you want to be?' it asked.

@c      `Oh, I'm not particular as to size,' Alice hastily replied;
@c    `only one doesn't like changing so often, you know.'

@c      `I DON'T know,' said the Caterpillar.

@c      Alice said nothing:  she had never been so much contradicted in
@c    her life before, and she felt that she was losing her temper.

@c      `Are you content now?' said the Caterpillar.

@c      `Well, I should like to be a LITTLE larger, sir, if you
@c    wouldn't mind,' said Alice:  `three inches is such a wretched
@c    height to be.'

@c      `It is a very good height indeed!' said the Caterpillar
@c    angrily, rearing itself upright as it spoke (it was exactly three
@c    inches high).

@c      `But I'm not used to it!' pleaded poor Alice in a piteous tone.
@c    And she thought of herself, `I wish the creatures wouldn't be so
@c    easily offended!'

@c      `You'll get used to it in time,' said the Caterpillar; and it
@c    put the hookah into its mouth and began smoking again.

@c      This time Alice waited patiently until it chose to speak again.
@c    In a minute or two the Caterpillar took the hookah out of its
@c    mouth and yawned once or twice, and shook itself.  Then it got
@c    down off the mushroom, and crawled away in the grass, merely
@c    remarking as it went, `One side will make you grow taller, and
@c    the other side will make you grow shorter.'

.i caku'i la .alis. denpa lenu cy di'a tavla .iba lo mentu be li pa
bi'i re ku le ciftoldi cu vimcu le nargile le moklu gi'e pamoi ja remoi
tengau le moklu gi'e desku .i cy cliva le gumri gi'e cpare le srasu le
darno gi'ecabo pikcusku po'o lu pa mlana cu clazenri'a do .ije le drata
mlana cu torzenri'a do li'u

@c      `One side of WHAT?  The other side of WHAT?' thought Alice to
@c    herself.

.i lu pa mlana be ba'e ma .e le drata mlana be ba'e ma li'u se pensi
la .alis.

@c      `Of the mushroom,' said the Caterpillar, just as if she had
@c    asked it aloud; and in another moment it was out of sight.

.i lu le gumri li'u se cusku le ciftoldi fi'o selmlu lenu tirna le
.abu selpensi .ibazibo canci

@c      Alice remained looking thoughtfully at the mushroom for a
@c    minute, trying to make out which were the two sides of it; and as
@c    it was perfectly round, she found this a very difficult question.
@c    However, at last she stretched her arms round it as far as they
@c    would go, and broke off a bit of the edge with each hand.

.i la .alis. pensi zgana le gumri ca'o lo mentu gi'e troci co facki
le re mlana gy .i gy prane cukla .iseni'ibo le nabmi cu camnandu
.iku'i .abu mo'uku tengau le birka ru'u le gumri ve'a le terku'e gi'e
sepi'o rore xance cu popygau le korbi le cmalu

@c      `And now which is which?' she said to herself, and nibbled a
@c    little of the right-hand bit to try the effect:  the next moment
@c    she felt a violent blow underneath her chin:  it had struck her
@c    foot!

.i lu .i ma fa'u ma mo fa'u mo li'u se cusku fi vo'e .i cmabatci le pritu
cmalu tezu'e lenu troci le selri'a .ibazibo ganse le vlile nundarxi le
xejni'a .i ri darxi le jamfu

@c      She was a good deal frightened by this very sudden change, but
@c    she felt that there was no time to be lost, as she was shrinking
@c    rapidly; so she set to work at once to eat some of the other bit.
@c    Her chin was pressed so closely against her foot, that there was
@c    hardly room to open her mouth; but she did it at last, and
@c    managed to swallow a morsel of the lefthand bit.

.i .abu carmi terpa le suksa nunstika .iku'i cinmo lu .ei na fesygau
le temci mu'i lenu mi sutra tolba'o li'u gi'e zukte lenu citka piso'u
le drata cmalu .i le .abu xedja cu tagji te damre le jamfu .iseri'a
carmi nandu fa lenu kargau le moklu .iku'i mo'uku kargau gi'e snada
lenu tulcti lo pagbu be le zunle cmalu

@c         *       *       *       *       *       *       *

@c             *       *       *       *       *       *

@c         *       *       *       *       *       *       *

@c      `Come, my head's free at last!' said Alice in a tone of
@c    delight, which changed into alarm in another moment, when she
@c    found that her shoulders were nowhere to be found:  all she could
@c    see, when she looked down, was an immense length of neck, which
@c    seemed to rise like a stalk out of a sea of green leaves that lay
@c    far below her.
lu .ua le stedu be mi zifre li'u se cusku la .alis fi'o tonga le ka gleki
poi bazi binxo le ka tepselspaji ca lenu facki le du'u na ka'e tolcri
kei le janco .i .abu fa'ani'a catlu gi'e viska lo tcebra clani cnebo po'o
poi stani simsa sanli le xamsi fi lo ni'azu crino pezli

@c      `What CAN all that green stuff be?' said Alice.  `And where
@c    HAVE my shoulders got to?  And oh, my poor hands, how is it I
@c    can't see you?'  She was moving them about as she spoke, but no
@c    result seemed to follow, except a little shaking among the
@c    distant green leaves.

@c      As there seemed to be no chance of getting her hands up to her
@c    head, she tried to get her head down to them, and was delighted
@c    to find that her neck would bend about easily in any direction,
@c    like a serpent.  She had just succeeded in curving it down into a
@c    graceful zigzag, and was going to dive in among the leaves, which
@c    she found to be nothing but the tops of the trees under which she
@c    had been wandering, when a sharp hiss made her draw back in a
@c    hurry:  a large pigeon had flown into her face, and was beating
@c    her violently with its wings.

@c      `Serpent!' screamed the Pigeon.
.i lu .ii since li'u se krica la tcacpi

@c      `I'm NOT a serpent!' said Alice indignantly.  `Let me alone!'
.i la .alis. fengu cusku lu mi ba'e na since .i .oi ko cliva mi li'u

@c      `Serpent, I say again!' repeated the Pigeon, but in a more
@c    subdued tone, and added with a kind of sob, `I've tried every
@c    way, and nothing seems to suit them!'
.i lu since .i mi ke'usku li'u milxe se rapsku la tcacpi .i ty klaku
jmina lu roda poi mi troci zo'u da ba'e na mapti li'u

@c      `I haven't the least idea what you're talking about,' said
@c    Alice.
.i lu mi jimpe noda le te tavla be do li'u se cusku la .alis.

@c      `I've tried the roots of trees, and I've tried banks, and I've
@c    tried hedges,' the Pigeon went on, without attending to her; `but
@c    those serpents!  There's no pleasing them!'
.i lu mi troci tu'a le tricu genja .ije mi troci tu'a le rirkoi .ije mi
troci tu'a le spabi'u sei le tcacpi cu cusku gi'e na jundi ko'a .iku'i
le since .o'onai se pluka noda li'u

@c      Alice was more and more puzzled, but she thought there was no
@c    use in saying anything more till the Pigeon had finished.
.i la .alis. zenba le ka cfipu ce'u .iku'i ko'a pensi le du'u zukte
le nu jmina cusku pu lenu la tcacpi cu tavla kei cu mulno kei noda kei

@c      `As if it wasn't trouble enough hatching the eggs,' said the
@c    Pigeon; `but I must be on the look-out for serpents night and
@c    day!  Why, I haven't had a wink of sleep these three weeks!'
.i lu nandu fa lenu kurji le sovda kei po'onai sei la tcacpi cu cusku
.ije ji'a mi kajde mi le since ca'o le nicte .e le donri .i ze'e le
jeftu be li ci ku mi sipna noda li'u

@c      `I'm very sorry you've been annoyed,' said Alice, who was
@c    beginning to see its meaning.
.i lu mi mutce xenru le nu do se fanza li'u se cusku la .alis. noi
co'a jimpe le smuni be le se cusku be ko'e

@c      `And just as I'd taken the highest tree in the wood,' continued
@c    the Pigeon, raising its voice to a shriek, `and just as I was
@c    thinking I should be free of them at last, they must needs come
@c    wriggling down from the sky!  Ugh, Serpent!'
.i lu mi posycu'a le tricu gafrai be le ricfoi sei le tcacpi cu krixa
zenba ke ranji cusku .icabo mi pensi ledu'u mi zifre fi le nu sincycau
.uo .i.ue torni klama fi le tsani .i .oi since li'u

@c      `But I'm NOT a serpent, I tell you!' said Alice.  `I'm a--I'm
@c    a--'
.i lu mi ba'e na since .i mi xu'asku di'u do sei la .alis. cu cusku .i mi
.y. mi li'u

@c      `Well!  WHAT are you?' said the Pigeon.  `I can see you're
@c    trying to invent something!'
.i lu do ba'e mo sei le tcacpi cu cusku .i mi zgana le du'u do troci
co finti da li'u

@c      `I--I'm a little girl,' said Alice, rather doubtfully, as she
@c    remembered the number of changes she had gone through that day.
.i lu mi .y. cmalu nixli li'u la .alis. se cusku co senpi ki'u lenu morji
le nu so'iroi selstika ca'o le ze'apu djedi

@c      `A likely story indeed!' said the Pigeon in a tone of the
@c    deepest contempt.  `I've seen a good many little girls in my
@c    time, but never ONE with such a neck as that!  No, no!  You're a
@c    serpent; and there's no use denying it.  I suppose you'll be
@c    telling me next that you never tasted an egg!'
.i lu lisri lakne .ianai sei le tcacpi cu tolsi'arai tonga cusku
.i mi ze'epu viska so'i cmalu nixli .eku'i nori se cnebu lo simsa
be ta .i .ienaicai .i do since .ije do nafsku .e'enai .i la'a do
bazi cusku le sedu'u do ze'epu na vu'izga lo sovda li'u

@c      `I HAVE tasted eggs, certainly,' said Alice, who was a very
@c    truthful child; `but little girls eat eggs quite as much as
@c    serpents do, you know.'
.i lu mi ja'a vu'izga lo sovda sei la .alis. noi mutce jetsku verba
cu cusku .iku'i za'a lo'e cmalu nixli cu dunli lo'e since le ni citka
lo sovda li'u

@c      `I don't believe it,' said the Pigeon; `but if they do, why
@c    then they're a kind of serpent, that's all I can say.'
.i le tcacpi cu cusku lu .ianai .i seni'ibo lo'e cmalu nixli cu
since da .i mi ja'o cusku di'u

@c      This was such a new idea to Alice, that she was quite silent
@c    for a minute or two, which gave the Pigeon the opportunity of
@c    adding, `You're looking for eggs, I know THAT well enough; and
@c    what does it matter to me whether you're a little girl or a
@c    serpent?'

i le sidbo tai cnino la alis ja'e le nu abu smaji ze'a lo mentu be
li paji'ire i la'e di'u curmi le nu le tcacpi cu jmina lu ju'osai
do sisku lo'e sovda i na vajni mi fa le du'u do cmalu nixli gi'ikau 
since li'u 

@c      `It matters a good deal to ME,' said Alice hastily; `but I'm
@c    not looking for eggs, as it happens; and if I was, I shouldn't
@c    want YOURS:  I don't like them raw.'

i lu mutce vajni ba'e mi sei la alis sutra cusku i ku'i mi na sisku
lo'e sovda ca'aku i ji'a romu'ei le du'u mi go'i kei mi na djija lei
me do moi i mi na nelci lo'e nalseljukpa sovda li'u 

@c      `Well, be off, then!' said the Pigeon in a sulky tone, as it
@c    settled down again into its nest.  Alice crouched down among the
@c    trees as well as she could, for her neck kept getting entangled
@c    among the branches, and every now and then she had to stop and
@c    untwist it.  After a while she remembered that she still held the
@c    pieces of mushroom in her hands, and she set to work very
@c    carefully, nibbling first at one and then at the other, and
@c    growing sometimes taller and sometimes shorter, until she had
@c    succeeded in bringing herself down to her usual height.

i lu ko cliva va'oku sei le tcacpi cu tolxendo tonga cusku li'u i ty
za'ure'u zutse le ty zdani i la alis dzikla le jbini be lei tricu tai
le abu cnebo ku joi lei jimca cu za'o se jgena i so'iroiku abu bilga
le nu tolselto'i cy i baku abu morji le nu abu za'o jgari lei gumri
spisa lei xance i abu co'a junri zukte le nu citka pa spisa pamai e
le drata remai i abu su'oroi zenba gi'e su'oroi jdika iromai abu 
snada le nu tcaci clani 

@c      It was so long since she had been anything near the right size,
@c    that it felt quite strange at first; but she got used to it in a
@c    few minutes, and began talking to herself, as usual.  `Come,
@c    there's half my plan done now!  How puzzling all these changes
@c    are!  I'm never sure what I'm going to be, from one minute to
@c    another!  However, I've got back to my right size:  the next
@c    thing is, to get into that beautiful garden--how IS that to be
@c    done, I wonder?'  As she said this, she came suddenly upon an
@c    open place, with a little house in it about four feet high.
@c    `Whoever lives there,' thought Alice, `it'll never do to come
@c    upon them THIS size:  why, I should frighten them out of their
@c    wits!'  So she began nibbling at the righthand bit again, and did
@c    not venture to go near the house till she had brought herself
@c    down to nine inches high.
