@node    cimo'o, vomo'o, remo'o, Top
@chapter cimo'o [A Caucus-Race and a Long Tale]


@c                               CHAPTER III

@c                      A Caucus-Race and a Long Tale


@c      They were indeed a queer-looking party that assembled on the
@c    bank--the birds with draggled feathers, the animals with their
@c    fur clinging close to them, and all dripping wet, cross, and
@c    uncomfortable.

i je'u cizra simlu gunma co jmaji le se rirxe i lei cipni zo'u
seke dandu pimlu i lei danlu zo'u seke kerfa co snipa le
jibni be dy ije le romei zo'u cilmo carmi gi'e fengu
gi'e na'e kufra

@c      The first question of course was, how to get dry again:  they
@c    had a consultation about this, and after a few minutes it seemed
@c    quite natural to Alice to find herself talking familiarly with
@c    them, as if she had known them all her life.  Indeed, she had
@c    quite a long argument with the Lory, who at last turned sulky,
@c    and would only say, `I am older than you, and must know better';
@c    and this Alice would not allow without knowing how old it was,
@c    and, as the Lory positively refused to tell its age, there was no
@c    more to be said.

i le pamoi co preti cu li'a du'u ta'i makau rere'u sudga i casnu la'edi'u
ijebabo zi lo mentu be li so'u simlu le ka rarna kei fa le nu la alis
goi ko'a cu facki le du'u ko'a pendo tavla ra setaida'i le nu
ko'a se slabu ra roroi le nu ko'a jmive i je'u ko'a pu je'aze'u daupro
la cipnrlori noi uo badri carna gi'e cusku lu mi tolcitmau do gi'eja'ebo
@c stidi lu le cipnrlori li'u .i ro cipnrlori cu babgalo mi'e pier.
@c i mi tugni i po'o mi pu na djuno le du'u la'ozoi Lory zoi sinxa makau
@c ije mi lazni i ku'i zo babgalo ki'a
@c i lei vi se casnu sumti cu cmene ija'ebo mi pilno zo la enai zo le
@c mi'e adam
junmau li'u po'o ije la'edi'u zo'u la alis na curmi secau le nu
djuno le du'u ly jai nanca makau ije ki'u le nu la cipnrlori cu je'a tolsarxe
le nu cusku le du'u makau se jai nanca ly na se sumji se cusku

@c      At last the Mouse, who seemed to be a person of authority among
@c    them, called out, `Sit down, all of you, and listen to me!  I'LL
@c    soon make you dry enough!'  They all sat down at once, in a large
@c    ring, with the Mouse in the middle.  Alice kept her eyes
@c    anxiously fixed on it, for she felt sure she would catch a bad
@c    cold if she did not get dry very soon.

i uo la smacu noi simlu co catni ra cu krixa lu ko zutse doi rodo
gi'e tinju'i mi i ba'e mi cu bazi sudgau je'u do li'u i le romei cu
zutse caze'iku gi'e djine co se midju la smacu i la alis ca'o xanka catlu
sy ki'u le nu ko'a birti le du'u co'a bilma bai le nu na sudbi'o baziku

@c      `Ahem!' said the Mouse with an important air, `are you all ready?
@c    This is the driest thing I know.  Silence all round, if you please!
@c    "William the Conqueror, whose cause was favoured by the pope, was
@c    soon submitted to by the English, who wanted leaders, and had been
@c    of late much accustomed to usurpation and conquest.  Edwin and
@c    Morcar, the earls of Mercia and Northumbria--"'

i lu ta'a sei la smacu cu vajni simlu cusku xu ro do bredi i la'edi'e
cu sudrai lo'i se slabu be mi i ro ko smaji e'o i lu la uiliam poi
jamji'a ku noi se nelcu'a la papas cu pubaziki trubi'o loi glepre
ku noi ke'a turni djica gi'e puziku mutce co se slabu le nu trubasti je 
jamji'a i la eduin joi la morkar vu'ogoi lei turni be la mersias fa'u 
la nortumbrias li'u li'u

@c      `Ugh!' said the Lory, with a shiver.

i lu o'unai sei la cipnrlori cusku je desku li'u

@c      `I beg your pardon!' said the Mouse, frowning, but very
@c    politely:  `Did you speak?'

i lu ke'ope'u sei la smacu cu cusku je frumu jekeku'i clite mutce
i xu do cusku li'u

@c      `Not I!' said the Lory hastily.

i lu na'ebo mi sei la cipnrlori sutra co cusku li'u

@c      `I thought you did,' said the Mouse.  `--I proceed.  "Edwin and
@c    Morcar, the earls of Mercia and Northumbria, declared for him:
@c    and even Stigand, the patriotic archbishop of Canterbury, found
@c    it advisable--"'

i lu mi jinvi le du'u go'e sei la cmaci cu cusku i mi ca'o cusku i lu
la eduin joi la morkar vu'ogoi lei turni be la mersias fa'u la
nortumbrias cu xusra seva'u ubu ije la stigand ji'a goi le
naijgi ke ralju seljdagidva pe la kanterburis cu facki fi da fe le du'u se djica
li'u li'u

@c      `Found WHAT?' said the Duck.

i lu facki fi ba'e ma sei la datka cusku li'u

@c      `Found IT,' the Mouse replied rather crossly:  `of course you
@c    know what "it" means.'

i lu lu facki fi ba'e da li'u sei la smacu cu spudu co fengu milxe i li'a
do djuno le du'u zo da sinxa ma li'u

@c      `I know what "it" means well enough, when I find a thing,' said
@c    the Duck:  `it's generally a frog or a worm.  The question is,
@c    what did the archbishop find?'

i lu mi djuno je'u le du'u zo da sinxa makau kei ca le nu mi facki
sei la datka cu cusku fi da poi so'iroi banfi ja curnu i le preti
zo'u fi ma fa le ralju seljdagidva cu facki li'u

@c      The Mouse did not notice this question, but hurriedly went on,
@c    `"--found it advisable to go with Edgar Atheling to meet William
@c    and offer him the crown.  William's conduct at first was
@c    moderate.  But the insolence of his Normans--"  How are you
@c    getting on now, my dear?' it continued, turning to Alice as it
@c    spoke.

i la smacu cu na sanji le di'u preti i ku'i sutra co ranji cusku
lu lu facki fi da fe le du'u se djica fa le nu kansa la edgar atelin le nu
@c Lost in translation. Where did "da" go? -phma
@c Sorry, bad translation, added it. -adam
penmi la uiliam gi'e friti fi ubu fe le nu turni i le nuntra be la uiliam
ca le nu cfari cu fadni i ku'i le nuntolclite be lai norman ne ubu li'u 
@c Should be "lei se natmrnormane" or the like. "lai norman" means
@c a mass of people named Norman. -phma
i pei doi do iu sei sy ca'o cusku jecabo carcra be la alis li'u

@c      `As wet as ever,' said Alice in a melancholy tone:  `it doesn't
@c    seem to dry me at all.'

i lu cilmo du'i le ka pu cilmo sei la alis badri cusku i simlu
le ka nalmilxe ji'a co sudgau mi li'u

@c      `In that case,' said the Dodo solemnly, rising to its feet, `I
@c    move that the meeting adjourn, for the immediate adoption of more
@c    energetic remedies--'

i lu iseki'ubo sei la dodos junri cusku co sanli be fi lei tuple
i mi stidi le du'u le nu penmi cu tolcfa ki'u le nu pilno lo tolcadmau
danfu li'u

@c      `Speak English!' said the Eaglet.  `I don't know the meaning of
@c    half those long words, and, what's more, I don't believe you do
@c    either!'  And the Eaglet bent down its head to hide a smile:
@c    some of the other birds tittered audibly.

i lu ko tavla bau la lojban sei la cipnrxakuila cifnu cu cusku i mi
na se slabu le smuni be pisu'omu lei di'u clani valsi ije mi jinvi
le du'u do ji'a na go'i li'u i la cipnrxakuila cifnu cu krogau
le stedu mu'i le nu mipri le nu cisma i pisu'o lei drata cipni
cu mi'amli co se tirna

@c      `What I was going to say,' said the Dodo in an offended tone,
@c    `was, that the best thing to get us dry would be a Caucus-race.'

i lu le pubazi se cusku be mi sei la dodos se xrani cusku cu du'u
le traji co se jalge be le nu sudgau mi'o cu me la kaukus nu bajra
jivni li'u

@c      `What IS a Caucus-race?' said Alice; not that she wanted much
@c    to know, but the Dodo had paused as if it thought that SOMEBODY
@c    ought to speak, and no one else seemed inclined to say anything.

i lu ki'a me la kaukus nu bajra jivni sei la alis cusku li'u i ko'a
na'e mutce co djica le nu djuno i ku'i la dodos pu denpa setai
le nu dy jinvi le du'u ba'e da ei tavla ije no drata pu simlu le ka
djica le nu cusku de

@c      `Why,' said the Dodo, `the best way to explain it is to do it.'
@c    (And, as you might like to try the thing yourself, some winter
@c    day, I will tell you how the Dodo managed it.)

i lu je'u sei la dodos cusku le xagrai co ciksi tadji cu nu gasnu li'u 
to'i ji'a ki'uda'i le nu do djica le nu do ji'a troci ca lo dunra donri
kei mi cusku fi do fe le du'u la dodos gasnu makau toi

@c      First it marked out a race-course, in a sort of circle, (`the
@c    exact shape doesn't matter,' it said,) and then all the party
@c    were placed along the course, here and there.  There was no `One,
@c    two, three, and away,' but they began running when they liked,
@c    and left off when they liked, so that it was not easy to know
@c    when the race was over.  However, when they had been running half
@c    an hour or so, and were quite dry again, the Dodo suddenly called
@c    out `The race is over!' and they all crowded round it, panting,
@c    and asking, `But who has won?'

i pamai dy finti lei sinxa be le nunbajra klaji be'o noi cukla milxe
to lu le satci tarmi na vajni sei dy cusku li'u toi ibabo le romei
cu se punji fi le se klaji vijevaku i cusku no lu i pa i re i ci i ko bajra
li'u i ku'i co'a bajra ca le nu djica kei ije co'u bajra ca la nu djica
iseki'ubo na frili fa le nu djuno le du'u ca makau le nu bajra jivni cu
se fanmo i ku'i ca le nu pu bajra ca lo cacra be li pimuji'i gi'e je'a
sudga rere'uku kei la dodos spaji kixsku lu le nu jivni cu se fanmo li'u
ije le romei cu denmi sanli gi'e vasxu mutce gi'e te pretu fi 
lu i ku'i ma jinga li'u

@c      This question the Dodo could not answer without a great deal of
@c    thought, and it sat for a long time with one finger pressed upon
@c    its forehead (the position in which you usually see Shakespeare,
@c    in the pictures of him), while the rest waited in silence.  At
@c    last the Dodo said, `EVERYBODY has won, and all must have
@c    prizes.'

i le di'u preti zo'u la dodos na kakne co danfu secau le nu pensi
mutce ije dy zutse ze'uku ca le nu pa degji cu danre le firgapru
to le se tarmi be la ceikspir bei va'o lei pixra be ri toi
ca le nu lei drata cu denpa je smaji i uo la dodos cusku lu le
ba'e romei cu jinga ije le romei ei cu se jigne'u li'u

@c      `But who is to give the prizes?' quite a chorus of voices
@c    asked.

i lu i ku'i ma dunda lei se jinga sei le voksa so'imei je'u cu te preti li'u

@c      `Why, SHE, of course,' said the Dodo, pointing to Alice with
@c    one finger; and the whole party at once crowded round her,
@c    calling out in a confused way, `Prizes! Prizes!'

i lu li'a ba'e ta li'a li'u se cusku la dodos noi sinxa la alis
sepi'o pa degji ije le piromei bazi denmi je sanli je sruri ko'a
gi'e se cfipu kixsku lu se jinga i se jinga li'u

@c      Alice had no idea what to do, and in despair she put her hand
@c    in her pocket, and pulled out a box of comfits, (luckily the salt
@c    water had not got into it), and handed them round as prizes.
@c    There was exactly one a-piece all round.

i la alis cu na'e milxe ji'a co djuno le du'u ei gasnu makau ije ki'u
le nu dunku ko'a punji le xance le daski ije vimcu le bi'u tanxe
be lei titydja to u'a le silna djacu na nermu'u le tanxe toi
gi'e fairgau lei titydja neba'i lei se jinga i satci fa le nu ro zvati
cu te dunda pa titydja

@c      `But she must have a prize herself, you know,' said the Mouse.

i lu i ku'i ei jinga da fa ba'e ta li'a, sei la smacu cu cusku li'u

@c      `Of course,' the Dodo replied very gravely.  `What else have
@c    you got in your pocket?' he went on, turning to Alice.

i lu li'a sei la dodos cu spuda co junri i do ponse ma poi drati zi'epe
vi le daski pe do

@c      `Only a thimble,' said Alice sadly.

i lu lo tajgau po'o sei la alis badri cusku li'u

@c      `Hand it over here,' said the Dodo.

i lu ko dunda fi mi sei la dodos cusku li'u

@c      Then they all crowded round her once more, while the Dodo
@c    solemnly presented the thimble, saying `We beg your acceptance of
@c    this elegant thimble'; and, when it had finished this short
@c    speech, they all cheered.

@c      Alice thought the whole thing very absurd, but they all looked
@c    so grave that she did not dare to laugh; and, as she could not
@c    think of anything to say, she simply bowed, and took the thimble,
@c    looking as solemn as she could.

@c      The next thing was to eat the comfits:  this caused some noise
@c    and confusion, as the large birds complained that they could not
@c    taste theirs, and the small ones choked and had to be patted on
@c    the back.  However, it was over at last, and they sat down again
@c    in a ring, and begged the Mouse to tell them something more.

@c      `You promised to tell me your history, you know,' said Alice,
@c    `and why it is you hate--C and D,' she added in a whisper, half
@c    afraid that it would be offended again.

@c      `Mine is a long and a sad tale!' said the Mouse, turning to
@c    Alice, and sighing.

@c      `It IS a long tail, certainly,' said Alice, looking down with
@c    wonder at the Mouse's tail; `but why do you call it sad?'  And
@c    she kept on puzzling about it while the Mouse was speaking, so
@c    that her idea of the tale was something like this:--

@c    @format
@c                        `Fury said to a
@c                       mouse, That he
@c                     met in the
@c                   house,
@c                "Let us
@c                  both go to
@c                    law:  I will
@c                      prosecute
@c                        YOU.  --Come,
@c                           I'll take no
@c                            denial; We
@c                         must have a
@c                     trial:  For
@c                  really this
@c               morning I've
@c              nothing
@c             to do."
@c               Said the
@c                 mouse to the
@c                   cur, "Such
@c                     a trial,
@c                       dear Sir,
@c                             With
@c                         no jury
@c                      or judge,
@c                    would be
@c                  wasting
@c                 our
@c                  breath."
@c                   "I'll be
@c                     judge, I'll
@c                       be jury,"
@c                             Said
@c                        cunning
@c                          old Fury:
@c                         "I'll
@c                          try the
@c                             whole
@c                              cause,
@c                                 and
@c                            condemn
@c                           you
@c                          to
@c                           death."'
@c    @end format


@c      `You are not attending!' said the Mouse to Alice severely.
@c    `What are you thinking of?'

@c      `I beg your pardon,' said Alice very humbly:  `you had got to
@c    the fifth bend, I think?'

@c      `I had NOT!' cried the Mouse, sharply and very angrily.

@c      `A knot!' said Alice, always ready to make herself useful, and
@c    looking anxiously about her.  `Oh, do let me help to undo it!'

@c      `I shall do nothing of the sort,' said the Mouse, getting up
@c    and walking away.  `You insult me by talking such nonsense!'

@c      `I didn't mean it!' pleaded poor Alice.  `But you're so easily
@c    offended, you know!'

@c      The Mouse only growled in reply.

@c      `Please come back and finish your story!' Alice called after
@c    it; and the others all joined in chorus, `Yes, please do!' but
@c    the Mouse only shook its head impatiently, and walked a little
@c    quicker.

@c      `What a pity it wouldn't stay!' sighed the Lory, as soon as it
@c    was quite out of sight; and an old Crab took the opportunity of
@c    saying to her daughter `Ah, my dear!  Let this be a lesson to you
@c    never to lose YOUR temper!'  `Hold your tongue, Ma!' said the
@c    young Crab, a little snappishly.  `You're enough to try the
@c    patience of an oyster!'

@c      `I wish I had our Dinah here, I know I do!' said Alice aloud,
@c    addressing nobody in particular.  `She'd soon fetch it back!'

@c      `And who is Dinah, if I might venture to ask the question?'
@c    said the Lory.

@c      Alice replied eagerly, for she was always ready to talk about
@c    her pet:  `Dinah's our cat.  And she's such a capital one for
@c    catching mice you can't think!  And oh, I wish you could see her
@c    after the birds!  Why, she'll eat a little bird as soon as look
@c    at it!'

@c      This speech caused a remarkable sensation among the party.
@c    Some of the birds hurried off at once:  one old Magpie began
@c    wrapping itself up very carefully, remarking, `I really must be
@c    getting home; the night-air doesn't suit my throat!' and a Canary
@c    called out in a trembling voice to its children, `Come away, my
@c    dears!  It's high time you were all in bed!'  On various pretexts
@c    they all moved off, and Alice was soon left alone.

@c      `I wish I hadn't mentioned Dinah!' she said to herself in a
@c    melancholy tone.  `Nobody seems to like her, down here, and I'm
@c    sure she's the best cat in the world!  Oh, my dear Dinah!  I
@c    wonder if I shall ever see you any more!'  And here poor Alice
@c    began to cry again, for she felt very lonely and low-spirited.
@c    In a little while, however, she again heard a little pattering of
@c    footsteps in the distance, and she looked up eagerly, half hoping
@c    that the Mouse had changed his mind, and was coming back to
@c    finish his story.


